### PR TITLE
Add word boundary for preprocessor keywods

### LINKED ISSUE #31: Variable "Is_PragmaLexer" isn't correctly highlighted
image

It can be reproduced using the following code:

``` cpp
struct foo {
  bool isPragmaLexer() const {
    return Is_PragmaLexer;
  }

  bool Is_PragmaLexer;
};
```

### PR DESCRIPTION
**Pull request by condy0919**
It attempts to fix #31

### CODE REVIEW

**Comment by condy0919** [comment]
I forgot this PR ...

**Comment by ludwigpacifici** [comment]
Hello,

Apologies for the late reply. I agree the issue #31 is from this package. However, this PR breaks one test.

On the left, it's with this PR, on the right it's with master:
emacs-regression

Looking at the documentation of [`regexp-opt`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Functions.html), I tried `symbols` as additional argument, but it fails for the same reason. Parsing C++ with regexp is not an easy task. Do you mind to have another look at the fix?

**Comment by condy0919** [comment]
Sure. But could you take a look at another PR which is simple enough and irrelevant with this one?

**Comment by condy0919** [comment]
Updated in another PR #35

**Pull request closed without merging**
